web:
  container_name: web
  image: nginx:latest
  ports: 
    - "7070:80"
  volumes:
    - ./code:/code
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php  
php:
  container_name: php
  image: php-fpm7.1
  volumes:
    - ./code:/code